const { sequelize, Education, Aspirant } = require("./models");

const defaultEducations = [
  { id: 1, title: "B.E. / B.Tech. - Computer Science", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 2, title: "B.E. / B.Tech. - Information Technology", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 3, title: "B.E. / B.Tech. - Electronics & Communication", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 4, title: "B.E. / B.Tech. - Electrical", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 5, title: "B.E. / B.Tech. - Mechanical", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 6, title: "B.E. / B.Tech. - Civil", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 7, title: "B.E. / B.Tech. - Chemical", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 8, title: "B.E. / B.Tech. - Aerospace", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 9, title: "B.E. / B.Tech. - Automobile", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 10, title: "B.E. / B.Tech. - Biotechnology", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 11, title: "B.E. / B.Tech. - Environmental", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 12, title: "B.E. / B.Tech. - Industrial", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 13, title: "B.E. / B.Tech. - Instrumentation", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 14, title: "B.E. / B.Tech. - Marine", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 15, title: "B.E. / B.Tech. - Mining", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 16, title: "B.E. / B.Tech. - Other", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 17, title: "B.Sc. - Computer Science", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 18, title: "BCA", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 19, title: "B.Arch.", category: "Bachelor's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 20, title: "M.E. / M.Tech. - Computer Science", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 21, title: "M.E. / M.Tech. - Information Technology", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 22, title: "M.E. / M.Tech. - Electronics & Communication", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 23, title: "M.E. / M.Tech. - Electrical", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 24, title: "M.E. / M.Tech. - Mechanical", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 25, title: "M.E. / M.Tech. - Civil", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 26, title: "M.E. / M.Tech. - Chemical", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 27, title: "M.E. / M.Tech. - Aerospace", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 28, title: "M.E. / M.Tech. - Biotechnology", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 29, title: "M.E. / M.Tech. - Environmental", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 30, title: "M.E. / M.Tech. - Industrial", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 31, title: "M.E. / M.Tech. - Instrumentation", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 32, title: "M.E. / M.Tech. - Other", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 33, title: "M.Sc. - Computer Science", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 34, title: "MCA", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 35, title: "M.Arch.", category: "Master's - Engineering / Technology", sortOrder: 0, status: 1 },
  { id: 36, title: "B.A. - Economics", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 37, title: "B.A. - Political Science", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 38, title: "B.A. - History", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 39, title: "B.A. - Sociology", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 40, title: "B.A. - Psychology", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 41, title: "B.A. - English Literature", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 42, title: "B.A. - Geography", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 43, title: "B.A. - Philosophy", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 44, title: "B.A. - Other", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 45, title: "B.Com. - General", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 46, title: "B.Com. - Accounting & Finance", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 47, title: "B.Com. - Banking & Insurance", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 48, title: "B.Com. - Other", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 49, title: "B.Sc. - Physics", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 50, title: "B.Sc. - Chemistry", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 51, title: "B.Sc. - Mathematics", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 52, title: "B.Sc. - Biology", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 53, title: "B.Sc. - Microbiology", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 54, title: "B.Sc. - Biotechnology", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 55, title: "B.Sc. - Agriculture", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 56, title: "B.Sc. - Nursing", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 57, title: "B.Sc. - Statistics", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 58, title: "B.Sc. - Other", category: "Bachelor's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 59, title: "M.A. - Economics", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 60, title: "M.A. - Political Science", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 61, title: "M.A. - History", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 62, title: "M.A. - Sociology", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 63, title: "M.A. - Psychology", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 64, title: "M.A. - English Literature", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 65, title: "M.A. - Geography", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 66, title: "M.A. - Philosophy", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 67, title: "M.A. - Other", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 68, title: "M.Com. - General", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 69, title: "M.Com. - Accounting & Finance", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 70, title: "M.Com. - Banking & Insurance", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 71, title: "M.Com. - Other", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 72, title: "M.Sc. - Physics", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 73, title: "M.Sc. - Chemistry", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 74, title: "M.Sc. - Mathematics", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 75, title: "M.Sc. - Biology", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 76, title: "M.Sc. - Microbiology", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 77, title: "M.Sc. - Biotechnology", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 78, title: "M.Sc. - Agriculture", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 79, title: "M.Sc. - Statistics", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 80, title: "M.Sc. - Other", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 81, title: "MSW - Social Work", category: "Master's - Arts / Commerce / Science", sortOrder: 0, status: 1 },
  { id: 82, title: "BBA - General", category: "Bachelor's - Management", sortOrder: 0, status: 1 },
  { id: 83, title: "BBA - Finance", category: "Bachelor's - Management", sortOrder: 0, status: 1 },
  { id: 84, title: "BBA - Marketing", category: "Bachelor's - Management", sortOrder: 0, status: 1 },
  { id: 85, title: "BBA - Human Resources", category: "Bachelor's - Management", sortOrder: 0, status: 1 },
  { id: 86, title: "BBA - International Business", category: "Bachelor's - Management", sortOrder: 0, status: 1 },
  { id: 87, title: "BMS - Management Studies", category: "Bachelor's - Management", sortOrder: 0, status: 1 },
  { id: 88, title: "BBM - Business Management", category: "Bachelor's - Management", sortOrder: 0, status: 1 },
  { id: 89, title: "B.Hotel Management", category: "Bachelor's - Management", sortOrder: 0, status: 1 },
  { id: 90, title: "B.Retail Management", category: "Bachelor's - Management", sortOrder: 0, status: 1 },
  { id: 91, title: "Other", category: "Bachelor's - Management", sortOrder: 0, status: 1 },
  { id: 92, title: "MBA - General", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 93, title: "MBA - Finance", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 94, title: "MBA - Marketing", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 95, title: "MBA - Human Resources", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 96, title: "MBA - Operations", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 97, title: "MBA - International Business", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 98, title: "MBA - Information Technology", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 99, title: "MBA - Healthcare Management", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 100, title: "MBA - Agribusiness", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 101, title: "MMS - Management Studies", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 102, title: "PGDM", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 103, title: "M.Hotel Management", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 104, title: "Other", category: "Master's - Management", sortOrder: 0, status: 1 },
  { id: 105, title: "MBBS - General Medicine", category: "Bachelor's - Medicine", sortOrder: 0, status: 1 },
  { id: 106, title: "BDS - Dental Surgery", category: "Bachelor's - Medicine", sortOrder: 0, status: 1 },
  { id: 107, title: "BAMS - Ayurvedic Medicine", category: "Bachelor's - Medicine", sortOrder: 0, status: 1 },
  { id: 108, title: "BHMS - Homeopathic Medicine", category: "Bachelor's - Medicine", sortOrder: 0, status: 1 },
  { id: 109, title: "BUMS - Unani Medicine", category: "Bachelor's - Medicine", sortOrder: 0, status: 1 },
  { id: 110, title: "BNYS - Naturopathy & Yoga", category: "Bachelor's - Medicine", sortOrder: 0, status: 1 },
  { id: 111, title: "BVSc. - Veterinary Science", category: "Bachelor's - Medicine", sortOrder: 0, status: 1 },
  { id: 112, title: "BOT - Occupational Therapy", category: "Bachelor's - Medicine", sortOrder: 0, status: 1 },
  { id: 113, title: "BPT - Physiotherapy", category: "Bachelor's - Medicine", sortOrder: 0, status: 1 },
  { id: 114, title: "B.Optometry", category: "Bachelor's - Medicine", sortOrder: 0, status: 1 },
  { id: 115, title: "B.Audiology & Speech", category: "Bachelor's - Medicine", sortOrder: 0, status: 1 },
  { id: 116, title: "Other", category: "Bachelor's - Medicine", sortOrder: 0, status: 1 },
  { id: 117, title: "MD - General Medicine", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 118, title: "MD - Pediatrics", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 119, title: "MD - Dermatology", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 120, title: "MD - Psychiatry", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 121, title: "MD - Radiology", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 122, title: "MD - Pathology", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 123, title: "MD - Anaesthesiology", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 124, title: "MS - General Surgery", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 125, title: "MS - Orthopaedics", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 126, title: "MS - Ophthalmology", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 127, title: "MS - ENT", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 128, title: "MS - Obstetrics & Gynaecology", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 129, title: "MDS - Dental Surgery", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 130, title: "MCh - Super Specialty Surgery", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 131, title: "DM - Super Specialty Medicine", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 132, title: "MPT - Physiotherapy", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 133, title: "MOT - Occupational Therapy", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 134, title: "Other", category: "Master's - Medicine", sortOrder: 0, status: 1 },
  { id: 135, title: "B.Pharm. - Pharmacy", category: "Bachelor's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 136, title: "Pharm.D - Doctor of Pharmacy", category: "Bachelor's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 137, title: "B.Sc. Nursing", category: "Bachelor's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 138, title: "GNM - General Nursing & Midwifery", category: "Bachelor's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 139, title: "ANM - Auxiliary Nursing & Midwifery", category: "Bachelor's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 140, title: "Other", category: "Bachelor's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 141, title: "M.Pharm. - Pharmaceutics", category: "Master's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 142, title: "M.Pharm. - Pharmacology", category: "Master's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 143, title: "M.Pharm. - Pharmaceutical Chemistry", category: "Master's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 144, title: "M.Pharm. - Quality Assurance", category: "Master's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 145, title: "M.Pharm. - Other", category: "Master's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 146, title: "M.Sc. Nursing - Medical Surgical", category: "Master's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 147, title: "M.Sc. Nursing - Pediatric", category: "Master's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 148, title: "M.Sc. Nursing - Psychiatric", category: "Master's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 149, title: "M.Sc. Nursing - Community Health", category: "Master's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 150, title: "M.Sc. Nursing - Other", category: "Master's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 151, title: "Other", category: "Master's - Pharmacy / Nursing", sortOrder: 0, status: 1 },
  { id: 152, title: "LLB - General Law", category: "Bachelor's - Legal", sortOrder: 0, status: 1 },
  { id: 153, title: "LLB - Corporate Law", category: "Bachelor's - Legal", sortOrder: 0, status: 1 },
  { id: 154, title: "LLB - Criminal Law", category: "Bachelor's - Legal", sortOrder: 0, status: 1 },
  { id: 155, title: "LLB - Constitutional Law", category: "Bachelor's - Legal", sortOrder: 0, status: 1 },
  { id: 156, title: "BA LLB (Integrated)", category: "Bachelor's - Legal", sortOrder: 0, status: 1 },
  { id: 157, title: "B.Com LLB (Integrated)", category: "Bachelor's - Legal", sortOrder: 0, status: 1 },
  { id: 158, title: "BBA LLB (Integrated)", category: "Bachelor's - Legal", sortOrder: 0, status: 1 },
  { id: 159, title: "B.Sc. LLB (Integrated)", category: "Bachelor's - Legal", sortOrder: 0, status: 1 },
  { id: 160, title: "Other", category: "Bachelor's - Legal", sortOrder: 0, status: 1 },
  { id: 161, title: "LLM - General Law", category: "Master's - Legal", sortOrder: 0, status: 1 },
  { id: 162, title: "LLM - Corporate Law", category: "Master's - Legal", sortOrder: 0, status: 1 },
  { id: 163, title: "LLM - Criminal Law", category: "Master's - Legal", sortOrder: 0, status: 1 },
  { id: 164, title: "LLM - Constitutional Law", category: "Master's - Legal", sortOrder: 0, status: 1 },
  { id: 165, title: "LLM - International Law", category: "Master's - Legal", sortOrder: 0, status: 1 },
  { id: 166, title: "LLM - Intellectual Property Law", category: "Master's - Legal", sortOrder: 0, status: 1 },
  { id: 167, title: "LLM - Human Rights Law", category: "Master's - Legal", sortOrder: 0, status: 1 },
  { id: 168, title: "Other", category: "Master's - Legal", sortOrder: 0, status: 1 },
  { id: 169, title: "CA - Chartered Accountant", category: "Finance & Professional Courses", sortOrder: 0, status: 1 },
  { id: 170, title: "CS - Company Secretary", category: "Finance & Professional Courses", sortOrder: 0, status: 1 },
  { id: 171, title: "CMA / ICWAI - Cost Accountant", category: "Finance & Professional Courses", sortOrder: 0, status: 1 },
  { id: 172, title: "CFA - Chartered Financial Analyst", category: "Finance & Professional Courses", sortOrder: 0, status: 1 },
  { id: 173, title: "CFP - Certified Financial Planner", category: "Finance & Professional Courses", sortOrder: 0, status: 1 },
  { id: 174, title: "FRM - Financial Risk Manager", category: "Finance & Professional Courses", sortOrder: 0, status: 1 },
  { id: 175, title: "ACCA", category: "Finance & Professional Courses", sortOrder: 0, status: 1 },
  { id: 176, title: "CPA - Certified Public Accountant", category: "Finance & Professional Courses", sortOrder: 0, status: 1 },
  { id: 177, title: "Other", category: "Finance & Professional Courses", sortOrder: 0, status: 1 },
  { id: 178, title: "IAS - Indian Administrative Service", category: "Civil Services", sortOrder: 0, status: 1 },
  { id: 179, title: "IPS - Indian Police Service", category: "Civil Services", sortOrder: 0, status: 1 },
  { id: 180, title: "IFS - Indian Foreign Service", category: "Civil Services", sortOrder: 0, status: 1 },
  { id: 181, title: "IRS - Indian Revenue Service", category: "Civil Services", sortOrder: 0, status: 1 },
  { id: 182, title: "IES - Indian Engineering Service", category: "Civil Services", sortOrder: 0, status: 1 },
  { id: 183, title: "State Civil Services", category: "Civil Services", sortOrder: 0, status: 1 },
  { id: 184, title: "Other", category: "Civil Services", sortOrder: 0, status: 1 },
  { id: 185, title: "Ph.D. - Engineering / Technology", category: "Doctorate", sortOrder: 0, status: 1 },
  { id: 186, title: "Ph.D. - Science", category: "Doctorate", sortOrder: 0, status: 1 },
  { id: 187, title: "Ph.D. - Arts / Humanities", category: "Doctorate", sortOrder: 0, status: 1 },
  { id: 188, title: "Ph.D. - Commerce / Management", category: "Doctorate", sortOrder: 0, status: 1 },
  { id: 189, title: "Ph.D. - Medicine", category: "Doctorate", sortOrder: 0, status: 1 },
  { id: 190, title: "Ph.D. - Law", category: "Doctorate", sortOrder: 0, status: 1 },
  { id: 191, title: "Ph.D. - Agriculture", category: "Doctorate", sortOrder: 0, status: 1 },
  { id: 192, title: "Ph.D. - Education", category: "Doctorate", sortOrder: 0, status: 1 },
  { id: 193, title: "Post Doctorate", category: "Doctorate", sortOrder: 0, status: 1 },
  { id: 194, title: "Other", category: "Doctorate", sortOrder: 0, status: 1 },
  { id: 195, title: "Diploma - Engineering", category: "Diploma / Polytechnic", sortOrder: 0, status: 1 },
  { id: 196, title: "Diploma - Computer Science / IT", category: "Diploma / Polytechnic", sortOrder: 0, status: 1 },
  { id: 197, title: "Diploma - Pharmacy", category: "Diploma / Polytechnic", sortOrder: 0, status: 1 },
  { id: 198, title: "Diploma - Nursing", category: "Diploma / Polytechnic", sortOrder: 0, status: 1 },
  { id: 199, title: "Diploma - Architecture", category: "Diploma / Polytechnic", sortOrder: 0, status: 1 },
  { id: 200, title: "Diploma - Hotel Management", category: "Diploma / Polytechnic", sortOrder: 0, status: 1 },
  { id: 201, title: "Diploma - Fashion Design", category: "Diploma / Polytechnic", sortOrder: 0, status: 1 },
  { id: 202, title: "Diploma - Graphic Design", category: "Diploma / Polytechnic", sortOrder: 0, status: 1 },
  { id: 203, title: "Diploma - Business Administration", category: "Diploma / Polytechnic", sortOrder: 0, status: 1 },
  { id: 204, title: "Diploma - Education (D.Ed.)", category: "Diploma / Polytechnic", sortOrder: 0, status: 1 },
  { id: 205, title: "ITI - Industrial Training", category: "Diploma / Polytechnic", sortOrder: 0, status: 1 },
  { id: 206, title: "Other", category: "Diploma / Polytechnic", sortOrder: 0, status: 1 },
  { id: 207, title: "12th - Science (PCM)", category: "Higher Secondary (12th)", sortOrder: 0, status: 1 },
  { id: 208, title: "12th - Science (PCB)", category: "Higher Secondary (12th)", sortOrder: 0, status: 1 },
  { id: 209, title: "12th - Commerce", category: "Higher Secondary (12th)", sortOrder: 0, status: 1 },
  { id: 210, title: "12th - Arts / Humanities", category: "Higher Secondary (12th)", sortOrder: 0, status: 1 },
  { id: 211, title: "12th - Vocational", category: "Higher Secondary (12th)", sortOrder: 0, status: 1 },
  { id: 212, title: "Other", category: "Higher Secondary (12th)", sortOrder: 0, status: 1 },
  { id: 213, title: "SSC / Matriculation", category: "Secondary (10th)", sortOrder: 0, status: 1 },
  { id: 214, title: "CBSE - 10th", category: "Secondary (10th)", sortOrder: 0, status: 1 },
  { id: 215, title: "ICSE - 10th", category: "Secondary (10th)", sortOrder: 0, status: 1 },
  { id: 216, title: "State Board - 10th", category: "Secondary (10th)", sortOrder: 0, status: 1 },
  { id: 217, title: "Other", category: "Secondary (10th)", sortOrder: 0, status: 1 },
  { id: 218, title: "Other", category: "Other", sortOrder: 0, status: 1 }
];

async function syncAndSeed() {
  try {
    console.log("Updating users table role ENUM...");
    try {
      await sequelize.query(
        "ALTER TABLE `users` MODIFY COLUMN `role` ENUM('professional', 'studio', 'institute', 'admin', 'aspirant') NOT NULL;"
      );
      console.log("Users table role ENUM updated successfully.");
    } catch (e) {
      console.log("Users table column update note:", e.message);
    }

    console.log("Syncing Educations table...");
    await Education.sync();
    console.log("Educations table synced successfully.");

    console.log("Syncing Aspirants table...");
    await Aspirant.sync();
    try {
      await sequelize.query("ALTER TABLE `aspirants` MODIFY COLUMN `photo_url` LONGTEXT NULL;");
    } catch (e) {
      console.log("Photo url alter note:", e.message);
    }
    console.log("Aspirants table synced successfully.");

    const count = await Education.count();
    if (count === 0) {
      console.log("Seeding default 218 education courses...");
      await Education.bulkCreate(defaultEducations);
      console.log("Educations seeded successfully.");
    } else {
      console.log(`Educations table already has ${count} records.`);
    }

    process.exit(0);
  } catch (err) {
    console.error("Failed to sync database:", err);
    process.exit(1);
  }
}

syncAndSeed();
